[project]
name = "ff-srl2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "newton-physics",
    "pyglet==2.1.3", # for some reason higher versions dont work for Przemek
    "pyopenhaptics>=1.0.1",
    "usd-core>=25.5.1",
    "warp-lang==1.8.0.dev20250618",
]


[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

[[tool.uv.index]]
url = "https://pypi.org/simple"

[tool.uv.sources]
newton-physics = { path = "../newton", editable = true }
warp-lang = { index = "nvidia"}